# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtracker.proto\x12\x07tracker\"\x8a\x01\n\x14\x43reateTrackedRequest\x12\x0e\n\x06userID\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05\x63over\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\r\n\x05genre\x18\x06 \x01(\t\x12\x0e\n\x06rating\x18\x07 \x01(\t\"9\n\x15\x43reateTrackedResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x12GetTrackedsRequest\x12\x0e\n\x06userID\x18\x01 \x01(\x03\"E\n\x13GetTrackedsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x86\x01\n\x14UpdateTrackedRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05\x63over\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\r\n\x05genre\x18\x06 \x01(\t\x12\x0e\n\x06rating\x18\x07 \x01(\t\"9\n\x15UpdateTrackedResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x14\x44\x65leteTrackedRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"9\n\x15\x44\x65leteTrackedResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd2\x02\n\x0eTrackerService\x12P\n\rCreateTracked\x12\x1d.tracker.CreateTrackedRequest\x1a\x1e.tracker.CreateTrackedResponse\"\x00\x12J\n\x0bGetTrackeds\x12\x1b.tracker.GetTrackedsRequest\x1a\x1c.tracker.GetTrackedsResponse\"\x00\x12P\n\rUpdateTracked\x12\x1d.tracker.UpdateTrackedRequest\x1a\x1e.tracker.UpdateTrackedResponse\"\x00\x12P\n\rDeleteTracked\x12\x1d.tracker.DeleteTrackedRequest\x1a\x1e.tracker.DeleteTrackedResponse\"\x00\x42\nZ\x08/trackerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010/tracker'
  _CREATETRACKEDREQUEST._serialized_start=27
  _CREATETRACKEDREQUEST._serialized_end=165
  _CREATETRACKEDRESPONSE._serialized_start=167
  _CREATETRACKEDRESPONSE._serialized_end=224
  _GETTRACKEDSREQUEST._serialized_start=226
  _GETTRACKEDSREQUEST._serialized_end=262
  _GETTRACKEDSRESPONSE._serialized_start=264
  _GETTRACKEDSRESPONSE._serialized_end=333
  _UPDATETRACKEDREQUEST._serialized_start=336
  _UPDATETRACKEDREQUEST._serialized_end=470
  _UPDATETRACKEDRESPONSE._serialized_start=472
  _UPDATETRACKEDRESPONSE._serialized_end=529
  _DELETETRACKEDREQUEST._serialized_start=531
  _DELETETRACKEDREQUEST._serialized_end=565
  _DELETETRACKEDRESPONSE._serialized_start=567
  _DELETETRACKEDRESPONSE._serialized_end=624
  _TRACKERSERVICE._serialized_start=627
  _TRACKERSERVICE._serialized_end=965
# @@protoc_insertion_point(module_scope)
