// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: tracked.proto

package tracker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrackedServiceClient is the client API for TrackedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackedServiceClient interface {
	CreateTracked(ctx context.Context, in *CreateTrackedRequest, opts ...grpc.CallOption) (*CreateTrackedResponse, error)
	GetTrackeds(ctx context.Context, in *GetTrackedsRequest, opts ...grpc.CallOption) (*GetTrackedsResponse, error)
	UpdateTracked(ctx context.Context, in *UpdateTrackedRequest, opts ...grpc.CallOption) (*UpdateTrackedResponse, error)
	DeleteTracked(ctx context.Context, in *DeleteTrackedRequest, opts ...grpc.CallOption) (*DeleteTrackedResponse, error)
}

type trackedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackedServiceClient(cc grpc.ClientConnInterface) TrackedServiceClient {
	return &trackedServiceClient{cc}
}

func (c *trackedServiceClient) CreateTracked(ctx context.Context, in *CreateTrackedRequest, opts ...grpc.CallOption) (*CreateTrackedResponse, error) {
	out := new(CreateTrackedResponse)
	err := c.cc.Invoke(ctx, "/tracker.TrackedService/CreateTracked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackedServiceClient) GetTrackeds(ctx context.Context, in *GetTrackedsRequest, opts ...grpc.CallOption) (*GetTrackedsResponse, error) {
	out := new(GetTrackedsResponse)
	err := c.cc.Invoke(ctx, "/tracker.TrackedService/GetTrackeds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackedServiceClient) UpdateTracked(ctx context.Context, in *UpdateTrackedRequest, opts ...grpc.CallOption) (*UpdateTrackedResponse, error) {
	out := new(UpdateTrackedResponse)
	err := c.cc.Invoke(ctx, "/tracker.TrackedService/UpdateTracked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackedServiceClient) DeleteTracked(ctx context.Context, in *DeleteTrackedRequest, opts ...grpc.CallOption) (*DeleteTrackedResponse, error) {
	out := new(DeleteTrackedResponse)
	err := c.cc.Invoke(ctx, "/tracker.TrackedService/DeleteTracked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackedServiceServer is the server API for TrackedService service.
// All implementations must embed UnimplementedTrackedServiceServer
// for forward compatibility
type TrackedServiceServer interface {
	CreateTracked(context.Context, *CreateTrackedRequest) (*CreateTrackedResponse, error)
	GetTrackeds(context.Context, *GetTrackedsRequest) (*GetTrackedsResponse, error)
	UpdateTracked(context.Context, *UpdateTrackedRequest) (*UpdateTrackedResponse, error)
	DeleteTracked(context.Context, *DeleteTrackedRequest) (*DeleteTrackedResponse, error)
	mustEmbedUnimplementedTrackedServiceServer()
}

// UnimplementedTrackedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrackedServiceServer struct {
}

func (UnimplementedTrackedServiceServer) CreateTracked(context.Context, *CreateTrackedRequest) (*CreateTrackedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTracked not implemented")
}
func (UnimplementedTrackedServiceServer) GetTrackeds(context.Context, *GetTrackedsRequest) (*GetTrackedsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackeds not implemented")
}
func (UnimplementedTrackedServiceServer) UpdateTracked(context.Context, *UpdateTrackedRequest) (*UpdateTrackedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTracked not implemented")
}
func (UnimplementedTrackedServiceServer) DeleteTracked(context.Context, *DeleteTrackedRequest) (*DeleteTrackedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTracked not implemented")
}
func (UnimplementedTrackedServiceServer) mustEmbedUnimplementedTrackedServiceServer() {}

// UnsafeTrackedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackedServiceServer will
// result in compilation errors.
type UnsafeTrackedServiceServer interface {
	mustEmbedUnimplementedTrackedServiceServer()
}

func RegisterTrackedServiceServer(s grpc.ServiceRegistrar, srv TrackedServiceServer) {
	s.RegisterService(&TrackedService_ServiceDesc, srv)
}

func _TrackedService_CreateTracked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrackedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackedServiceServer).CreateTracked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tracker.TrackedService/CreateTracked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackedServiceServer).CreateTracked(ctx, req.(*CreateTrackedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackedService_GetTrackeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackedServiceServer).GetTrackeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tracker.TrackedService/GetTrackeds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackedServiceServer).GetTrackeds(ctx, req.(*GetTrackedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackedService_UpdateTracked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrackedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackedServiceServer).UpdateTracked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tracker.TrackedService/UpdateTracked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackedServiceServer).UpdateTracked(ctx, req.(*UpdateTrackedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackedService_DeleteTracked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrackedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackedServiceServer).DeleteTracked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tracker.TrackedService/DeleteTracked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackedServiceServer).DeleteTracked(ctx, req.(*DeleteTrackedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackedService_ServiceDesc is the grpc.ServiceDesc for TrackedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracker.TrackedService",
	HandlerType: (*TrackedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTracked",
			Handler:    _TrackedService_CreateTracked_Handler,
		},
		{
			MethodName: "GetTrackeds",
			Handler:    _TrackedService_GetTrackeds_Handler,
		},
		{
			MethodName: "UpdateTracked",
			Handler:    _TrackedService_UpdateTracked_Handler,
		},
		{
			MethodName: "DeleteTracked",
			Handler:    _TrackedService_DeleteTracked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracked.proto",
}
